# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_center', '0002_userprofile_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='default@gmail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
