# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_center', '0003_auto_20160827_1527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
    ]
