# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_center', '0005_auto_20160828_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='credibilityRating',
            field=models.FloatField(default='5'),
        ),
        migrations.AddField(
            model_name='report',
            name='numberOfRaters',
            field=models.IntegerField(default='0'),
        ),
    ]
