# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_center', '0005_auto_20160827_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='dateTimeEnd',
        ),
    ]
