# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_center', '0006_remove_report_datetimeend'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dateTimeEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='dateTimeStart',
            field=models.DateTimeField(null=True),
        ),
    ]
