# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_center', '0008_userprofile_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimedPrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=30)),
                ('pointCost', models.IntegerField(default=0)),
                ('code', models.CharField(default='default', max_length=30)),
                ('taken', models.BooleanField(default=False)),
                ('claimed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='p@ssword', max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportType',
            field=models.CharField(choices=[('Flood', 'Flood'), ('Traffic', 'Traffic'), ('LandSlide', 'LandSlide'), ('Road Accident', 'Road Accident'), ('Fire Alert', 'Fire Alert')], max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster_center.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(default='default', max_length=15),
        ),
        migrations.AddField(
            model_name='prize',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='disaster_center.UserProfile'),
        ),
        migrations.AddField(
            model_name='claimedprize',
            name='prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster_center.Prize'),
        ),
        migrations.AddField(
            model_name='claimedprize',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster_center.UserProfile'),
        ),
    ]
