# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_center', '0009_auto_20160827_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportType',
            field=models.CharField(choices=[('Flood', 'Flood'), ('Traffic', 'Traffic'), ('LandSlide', 'LandSlide'), ('Road Accident', 'Road Accident'), ('Tidal Wave', 'Tidal Wave'), ('Fire Alert', 'Fire Alert')], max_length=30),
        ),
    ]
