# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_center', '0010_auto_20160827_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='report',
            name='reportType',
            field=models.CharField(choices=[('Flood', 'Flood'), ('Traffic', 'Traffic'), ('LandSlide', 'LandSlide'), ('Road Accident', 'Road Accident'), ('Fire Alert', 'Fire Alert')], max_length=30),
        ),
    ]
